version: '3'
services:
  grunt:
    image: grunt
    expose:
      - "9901"
    environment:
      ADVERTISED_HOST: grunt
      ADVERTISED_PORT: 9901
      CONSUL_PORT: 8500
      CONSUL_HOST: consul
    links:
      - consul

  slicer:
    image: mayoqin/slicer
    expose:
      - "9901"
    environment:
      ADVERTISED_HOST: slicer
      ADVERTISED_PORT: 9901
      CONSUL_PORT: 8500
      CONSUL_HOST: consul
    links:
      - consul

  dcmqi:
    image: mayoqin/dcmqi
    expose:
      - "9901"
    environment:
      ADVERTISED_HOST: dcmqi
      ADVERTISED_PORT: 9901
      CONSUL_PORT: 8500
      CONSUL_HOST: consul
    links:
      - consul

  consul:
    image: consul
    expose:
      - "8500"
    ports:
      - "8500:8500"
